### ISSUE TITLE
CK2 Save File Error: Latin Characters

### ISSUE THREAD

**Issue by OwenDurkin** [Shadark/ClauseWizard#3]
I am trying to parse CK2 files using this project and I am running into an issue where `codecs.py` fails to decode latin characters. I've tested this code on a few save files and they each run into this issue where it can't handle one of these weird characters.

Save File:
[West_Francia_Test.ck2](https://drive.google.com/file/d/1MFiNk6Cu_lSVSGJQjjm1UdNebf69EUjH/view?usp=sharing)

Code:
```
# test.py
import ClauseWizard

tokens = None
with open('./West_Francia_Test.ck2') as f:
    tokens = ClauseWizard.cwparse(f.read())
```

Error message:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    tokens = ClauseWizard.cwparse(f.read())
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 7022: invalid continuation byte
```

**Comment by OwenDurkin** [comment]
My bad-  I forgot that python's default `f.read()` doesn't work on CK2 files,
and that is what is causing the error in the original piece of code.

To anyone interested, the solution to this problem is to read the file using the encoding Windows-1252 as follows

```
# test.py
import ClauseWizard
import io

tokens = None
with io.open('./West_Francia_Test.ck2', encoding="cp1252") as f:
    tokens = ClauseWizard.cwparse(f.read())
```
